import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BottomBar from "@/components/BottomBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "@Soklay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen relative overflow-hidden">
          {children}
          <BottomBar/>
        </div>
      </body>
    </html>
  );
}
